### PR TITLE
Update README for pipenv

### LINKED ISSUE #4: Add Pipenv
Add pipenv to Okra

### PR DESCRIPTION
**Pull request by treble37**
Closes #4

### CODE REVIEW

**Comment by treble37** [comment]
@tbonza - added pipenv - can I remove the whole setup.py file (I see a reference to a script `bin/okra` which looks like might be needed)....??

We could also tell them to pipenv run perhaps - https://github.com/pypa/pipenv/issues/2921

**Comment by tbonza** [comment]
Let's keep the `python setup.py install` line for now but possibly add a comment that it's only meant for installation of the development version. Considering [pep-0518](https://www.python.org/dev/peps/pep-0518), we may be able replace setuptools with pipenv sometime in the future

**Comment by treble37** [comment]
I also removed `install_requires` from setup.py since we have the Pipfile, and I assume that will install the right dependencies...

**Review by tbonza — APPROVED** [review]
This LGTM, thanks!

**Pull request merged**
